# Generated by Django 3.1 on 2020-08-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerecog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ihadetails',
            old_name='file',
            new_name='actualfile',
        ),
    ]
