# Generated by Django 3.1 on 2020-08-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecog', '0002_auto_20200816_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='IhaTestDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actualtestfile', models.BinaryField()),
                ('filename', models.CharField(max_length=256)),
                ('tid', models.IntegerField()),
            ],
            options={
                'db_table': 'IhaTestDetails',
            },
        ),
    ]
