# Generated by Django 3.0.8 on 2020-07-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecog', '0005_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'InsDetails',
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='CollegeDetails',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='EmpDetails',
        ),
        migrations.DeleteModel(
            name='LoginCredentials',
        ),
    ]
